name: Renovate
on:
  schedule:
    - cron: 13 */4 * * *

  pull_request:
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

  push:
    branches:
      - main
    paths:
      - .github/renovate-config.json5
      - .github/workflows/renovate.yml

  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode"
        required: false
        default: false
        type: boolean

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/renovate-config.json5

      - uses: renovatebot/github-action@f24426972367551f3391720e34317783a92fd32b # v41.0.8
        with:
          configurationFile: .github/renovate-config.json5
          # renovate: datasource=docker depName=ghcr.io/renovatebot/renovate
          renovate-version: 39.91.0@sha256:60d04619493d43fe67d728121dfef56b893bf90695219d352e772e881403d158
          token: ${{ secrets.RENOVATE }}
        env:
          LOG_LEVEL: ${{ github.event_name == 'pull_request' && 'debug' || 'info' }}
          # On pull requests, use the branch HEAD ref, so you can change things and see the results in the PR workflow run.
          # By default, Renovate will clone the main/default branch.
          RENOVATE_BASE_BRANCHES: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || null }}
          # Dry run if the event is pull_request, or workflow_dispatch AND the dry-run input is true
          RENOVATE_DRY_RUN: ${{ (github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true')) && 'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: RenovateBot
